on:
  push:
    branches: [main]
    workflow_dispatch:
name: 🚀 Deploy website on push
jobs:
  job_one:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
        - name: testing vps ssh connextion
          uses: appleboy/ssh-action@master
          with:
            host: 172.105.19.227
            username: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              cd /var/www/
              git clone https://github.com/Lumina-Institute/Demo.git
              python3 -m invoke deploy
